"""add_is_deleted_fields_for_logical_deletion

Revision ID: 0036c61b16e1
Revises: 754361c42e5e
Create Date: 2025-12-03 06:18:10.259011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0036c61b16e1'
down_revision: Union[str, None] = '754361c42e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加 is_deleted 字段，默认值为 False
    op.add_column('score_exchanges', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('score_exchanges', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_score_exchanges_is_deleted'), 'score_exchanges', ['is_deleted'], unique=False)
    
    op.add_column('score_increases', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('score_increases', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_score_increases_is_deleted'), 'score_increases', ['is_deleted'], unique=False)
    
    op.add_column('students', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('students', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_students_is_deleted'), 'students', ['is_deleted'], unique=False)
    
    op.add_column('tasks', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('tasks', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tasks_is_deleted'), 'tasks', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_is_deleted'), table_name='tasks')
    op.drop_column('tasks', 'deleted_at')
    op.drop_column('tasks', 'is_deleted')
    op.drop_index(op.f('ix_students_is_deleted'), table_name='students')
    op.drop_column('students', 'deleted_at')
    op.drop_column('students', 'is_deleted')
    op.drop_index(op.f('ix_score_increases_is_deleted'), table_name='score_increases')
    op.drop_column('score_increases', 'deleted_at')
    op.drop_column('score_increases', 'is_deleted')
    op.drop_index(op.f('ix_score_exchanges_is_deleted'), table_name='score_exchanges')
    op.drop_column('score_exchanges', 'deleted_at')
    op.drop_column('score_exchanges', 'is_deleted')
    # ### end Alembic commands ###
